"""
Nightingale Report Generator
Generates structured incident reports
"""
from datetime import datetime
from typing import List

from nightingale.types import (
    IncidentEvent, FixPlan, VerificationResult,
    ConfidenceFactors, AttemptRecord, MetricsData,
    IncidentReport, DecisionType
)


class EscalationReporter:
    """
    Generates comprehensive incident reports.
    """
    
    def generate_report(
        self,
        event: IncidentEvent,
        plan: FixPlan,
        result: VerificationResult,
        confidence: float,
        factors: ConfidenceFactors,
        decision: str,
        attempts: List[AttemptRecord],
        metrics: MetricsData
    ) -> IncidentReport:
        """
        Generate structured incident report.
        
        Args:
            event: Original incident
            plan: Final fix plan
            result: Final verification result
            confidence: Final confidence score
            factors: Confidence factors breakdown
            decision: Resolution decision
            attempts: All attempt records
            metrics: Performance metrics
            
        Returns:
            IncidentReport with full details
        """
        decision_type = DecisionType.RESOLVE if decision == "resolve" else DecisionType.ESCALATE
        
        report_text = self._generate_markdown(
            event, plan, result, confidence, factors, decision, attempts, metrics
        )
        
        return IncidentReport(
            incident_id=event.id,
            decision=decision_type,
            confidence=confidence,
            confidence_factors=factors,
            attempts=attempts,
            metrics=metrics,
            final_plan=plan,
            final_verification=result,
            report_text=report_text
        )
    
    def _generate_markdown(
        self,
        event: IncidentEvent,
        plan: FixPlan,
        result: VerificationResult,
        confidence: float,
        factors: ConfidenceFactors,
        decision: str,
        attempts: List[AttemptRecord],
        metrics: MetricsData
    ) -> str:
        """Generate markdown report text."""
        
        status_emoji = "✅" if decision == "resolve" else "⚠️"
        status_text = "AUTO-RESOLVED" if decision == "resolve" else "ESCALATED TO HUMAN"
        
        report = f"""# 🐦 Nightingale Incident Report

## Status: {status_emoji} {status_text}

| Metric | Value |
|--------|-------|
| **Incident ID** | `{event.id}` |
| **Confidence** | {confidence:.1%} |
| **Decision** | {decision.upper()} |
| **Attempts** | {len(attempts)} |
| **Duration** | {metrics.total_duration_ms}ms |

---

## 📋 Incident Details

- **Type**: {event.type.value}
- **Repository**: `{event.repository_path}`
- **Branch**: {event.branch}
- **Commit**: `{event.commit_sha}`
"""
        
        if event.failed_steps:
            step = event.failed_steps[-1]
            report += f"""
### Failed Step
- **Name**: {step.name}
- **Status**: {step.status}

```
{(step.logs or 'No logs')[:1000]}
```
"""
        
        report += f"""
---

## 🔍 Root Cause Analysis

{plan.root_cause or plan.rationale}

---

## 🔧 Fix Applied

**Rationale**: {plan.rationale}

**Risk Level**: {plan.risk_level.value.upper()}

### Files Changed
"""
        
        for f in plan.files_to_change:
            report += f"\n- `{f.file_path}` [{f.change_type}]\n"
        
        report += f"""
---

## 📊 Confidence Breakdown

| Factor | Score | Weight |
|--------|-------|--------|
| Test Pass Ratio | {factors.test_pass_ratio:.2f} | 35% |
| Inverse Blast Radius | {factors.inverse_blast_radius:.2f} | 25% |
| Attempt Penalty | {factors.attempt_penalty:.2f} | 15% |
| Risk Modifier | {factors.risk_modifier:.2f} | 15% |
| Self-Consistency | {factors.self_consistency_score:.2f} | 10% |
| **Weighted Total** | **{confidence:.2f}** | |

---

## ✅ Verification Results

- **Status**: {'PASSED' if result.success else 'FAILED'}
- **Tests Passed**: {result.tests_passed}/{result.tests_total}
- **Duration**: {result.duration_ms}ms

```
{result.output_log[-1500:]}
```

---

## 📈 Metrics

- **Total API Calls**: {metrics.total_api_calls}
- **Total Tokens**: {metrics.total_tokens_used}
- **Sandbox Runs**: {metrics.sandbox_runs}
- **Files Modified**: {metrics.files_modified}

---

*Generated by Nightingale v0.1.0 at {datetime.now().isoformat()}*
"""
        
        return report
    
    def generate_simple_report(
        self,
        event: IncidentEvent,
        plan: FixPlan,
        result: VerificationResult,
        score: float,
        decision: str
    ) -> str:
        """
        Generate simplified report for backward compatibility.
        """
        return f"""
# Nightingale Incident Report

**Status**: {decision.upper()}
**Confidence**: {score:.2f}

## Incident Details
- **ID**: {event.id}
- **Type**: {event.type}
- **Repo**: {event.repository_path}

## Diagnosis & Plan
**Rationale**: {plan.rationale}

## Verification
**Success**: {result.success}
**Logs**:
```
{result.output_log[-500:]}
```
"""
